# Generated by Django 3.0.6 on 2020-05-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='addresses/images/'),
        ),
    ]
